language: node_js
node_js:
  - '6'
install:
  - yarn
script:
  - yarn test
before_deploy:
  - yarn build
deploy:
  skip_cleanup: true
  provider: surge
  project: ./dist/
  domain: checkout-pricing-prototype.surge.sh
  on:
    branch: master
